Features[1.memberDeletefromComunity 2.nameConvention in MemberDetails…
spaceforcode/membership-service pull request #16
Opened 2023-07-05 12:58 UTC by royanik17

… 3. Remove CommunityId form member_list]

2023-07-06 01:38 UTC, ayanit84 requested changes
unit tests

2023-07-07 01:21 UTC, ayanit84 approved these changes
2 comments

2023-07-07 01:21 UTC, ayanit84 commented on src/main/java/com/experimental/product/community/membershipservice/client/request/CreateCommunityRequestV2.java
> +    public CreateCommunityRequestV2(String name, String description, String address, Map<ContactType, String> contacts, List<String> emergencyContacts, Boolean isGated, Boolean hasPool, Boolean hasGy
please move the constructor below all member variables. 
1. first member variables
2. then constructors
3. then public methods

2023-07-07 01:21 UTC, ayanit84 commented on src/test/java/com/experimental/product/community/membershipservice/controller/CommunityAdminControllerV2Test.java
> +
Good Job

2023-07-07 02:19 UTC, royanik17 commented on src/main/java/com/experimental/product/community/membershipservice/client/request/CreateCommunityRequestV2.java
> +    public CreateCommunityRequestV2(String name, String description, String address, Map<ContactType, String> contacts, List<String> emergencyContacts, Boolean isGated, Boolean hasPool, Boolean hasGy
Ok sure

2023-07-07 02:20 UTC, merged