Feature/api documentation
spaceforcode/membership-service pull request #19
Opened 2023-07-11 17:08 UTC by royanik17

API DOCUMENTATION

2023-07-14 03:06 UTC, ayanit84 requested changes
please check

2023-07-14 03:06 UTC, ayanit84 commented on README.md
> +- CommunityAdminControllerV2
remove community

2023-07-14 03:06 UTC, ayanit84 commented on README.md
> + -  Member Search Controller
do not use "controller" word

2023-07-14 03:06 UTC, ayanit84 commented on README.md
> +  - Response: `List<MemberResponseV2>`  - List of member details
List<Some Object> - no need to mention , just show the JSON structure

2023-07-17 11:47 UTC, royanik17 commented on README.md
> +- CommunityAdminControllerV2
Replace By API

2023-07-17 11:48 UTC, royanik17 commented on README.md
> + -  Member Search Controller
API

2023-07-17 11:48 UTC, royanik17 commented on README.md
> +  - Response: `List<MemberResponseV2>`  - List of member details
Fixed by using JSON Structure

2023-07-17 11:51 UTC, royanik17 commented
@ayanit84  Updated you can review it now

2023-08-12 04:37 UTC, ayanit84 approved these changes
looks good.

2023-08-12 05:42 UTC, merged