Admin controller/v2 api
spaceforcode/membership-service pull request #3
Opened 2023-05-08 17:23 UTC by royanik17

2023-05-08 19:48 UTC, ayanit84 commented
Fix the "out-of-date" branch

2023-05-08 19:48 UTC, ayanit84 commented
Make sure to use "Squash and merge" when merging
<img width="470" alt="image" src="https://user-images.githubusercontent.com/17430082/236919536-9359b753-acbd-4e30-80b4-bfbf1ba0e36a.png">

2023-05-08 19:49 UTC, ayanit84 requested changes
need changes

2023-05-09 04:52 UTC, royanik17 commented
OK

2023-05-10 05:26 UTC, royanik17 commented
H

2023-05-10 17:13 UTC, ayanit84 commented on src/main/java/com/experimental/product/community/membershipservice/sevice/MemberAdminServiceV2.java
> +                updatedMember = updatedMember.updatePaymentOptions(updateMemberRequest.getPaymentOptions());
what exactly it is doing? referring _ updatedMember_ and then again assigning to the same variable _ updatedMember_

2023-05-10 17:13 UTC, ayanit84 requested changes
please check

2023-05-15 03:53 UTC, ayanit84 approved these changes

2023-05-15 09:08 UTC, merged